#!/bin/bash
path_initial=$(pwd)

finish() {
	log "Exiting"
	cd "$path_initial" || exit
	rm -Rf tmp
}

# logging fn
log() {
	local color_on=$'\e[0;32m'
	local color_off=$'\e[0m'
	echo "${color_on}[$(date '+%Y-%m-%d %H:%M:%S %:z')]${color_off} $*" >&2
}

# error fn
fatal() {
	local color_fatal=$'\033[0;31m'
	log "${color_fatal} $* Failed!"
	log "${color_fatal}	Error!"
	finish
	exit 1
}


log "Installing neovim and it's dependencies"
sudo pacman -S neovim python python-pip ctags || 
	fatal "Installing packages"

log "Installing some AUR dependencies"
paru -S rusty-tags || 
    pacaur -S rusty-tags || 
    yaourt -S rusty-tags || 
    sudo cargo install --root / rusty-tags || 
    fatal "Installing additional AUR packages"

log "Istalling python dependencies"
pip install neovim ||
    fatal "Installing python dependencies"

log "Installing fonts"
( cd fonts && ./install.sh ) ||
	fatal "Installing powerline fonts"

log "Getting rid of old configuration"
rm -Rf ~/.config/nvim || fatal "Getting rid of old configuration"
log "Copying new configuration"
mkdir --parents ~/.config/nvim || fatal "Creation of .config/nvim directory"
cp -r config/. ~/.config/nvim/ || fatal "Copying new configs"

log "Script successfully finished"
finish
